### ISSUE TITLE
ImportError running  bin/train.py 

### ISSUE THREAD

**Issue by angelo337** [nicolas-ivanov/debug_seq2seq#18]
hi there
I am trying to start learning this code, however after i download and install everything I try to run your example code but I am getting this error, could you please point me out my mistake?
thanks a lot

$      sudo python bin/train.py 
INFO:gensim.utils:'pattern' package found; utils.lemmatize() is available for English
INFO:summa.preprocessing.cleaner:'pattern' package found; tag filters are available for English
Using Theano backend.
/usr/local/lib/python2.7/dist-packages/theano/tensor/signal/downsample.py:6: UserWarning: downsample module has been moved to the theano.tensor.signal.pool module.
  "downsample module has been moved to the theano.tensor.signal.pool module.")
Traceback (most recent call last):
  File "bin/train.py", line 10, in <module>
    from lib.nn_model.model import get_nn_model
  File "/home/creangel/Downloads/keras/seq2seq/debug_seq2seq/lib/nn_model/model.py", line 4, in <module>
    from seq2seq.models import SimpleSeq2seq
  File "build/bdist.linux-x86_64/egg/seq2seq/__init__.py", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/seq2seq/cells.py", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/recurrentshop/__init__.py", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/recurrentshop/engine.py", line 1, in <module>
ImportError: cannot import name Layer

**Comment by lijuncheng16** [comment]
SimpleSeq2seq has changed to SimpleSeq2Seq. Typo due to updates...

**Comment by jianboyang** [comment]
I have the same error, even after changing SImpleSeq2seq to SimpleSeq2Seq

INFO:summa.preprocessing.cleaner:'pattern' package not found; tag filters are not available for English
Using Theano backend.
Traceback (most recent call last):
  File "bin/train.py", line 10, in <module>
    from lib.nn_model.model import get_nn_model
  File "/Users/212461546/Box Sync/gProject/SmartSignal/_TagMapping/code/DL/debug_seq2seq/lib/nn_model/model.py", line 4, in <module>
    from seq2seq.models import SimpleSeq2Seq
  File "build/bdist.macosx-10.7-x86_64/egg/seq2seq/__init__.py", line 1, in <module>
  File "build/bdist.macosx-10.7-x86_64/egg/seq2seq/cells.py", line 1, in <module>
ImportError: cannot import name weight
