### ISSUE TITLE
ValueError: numpy.dtype has the wrong size, try recompiling

### ISSUE THREAD

**Issue by llSourcell** [nicolas-ivanov/debug_seq2seq#2]
I get the following error when running bin/train.py 

1482-sraval:debug_seq2seq sraval$ python bin/train.py 
Traceback (most recent call last):
  File "bin/train.py", line 9, in <module>
    from lib.w2v_model import w2v
  File "/Users/sraval/Desktop/yooo/debug_seq2seq/lib/w2v_model/w2v.py", line 4, in <module>
    from gensim.models import Word2Vec
  File "/Library/Python/2.7/site-packages/gensim/__init__.py", line 6, in <module>
    from gensim import parsing, matutils, interfaces, corpora, models, similarities, summarization
  File "/Library/Python/2.7/site-packages/gensim/models/__init__.py", line 13, in <module>
    from .word2vec import Word2Vec
  File "/Library/Python/2.7/site-packages/gensim/models/word2vec.py", line 100, in <module>
    from gensim.models.word2vec_inner import train_sentence_sg, train_sentence_cbow, FAST_VERSION,\
  File "__init__.pxd", line 155, in init gensim.models.word2vec_inner (./gensim/models/word2vec_inner.c:9234)
ValueError: numpy.dtype has the wrong size, try recompiling

**Comment by nicolas-ivanov** [comment]
@llSourcell please add a brief solution of your problem here to ease the life of other people who will be faced with. Also consider wrapping the output of your code with \`\`\` \`\`\` since it makes your message ten times more readable.
