### ISSUE TITLE
Cannot import name initializers

### ISSUE THREAD

**Issue by hieuthehungry** [nicolas-ivanov/debug_seq2seq#32]
I was trying to run this code on Python 2.7, Ubuntu 16.04. But it looks like i'm having some import error. This is my error's log:

"Traceback (most recent call last):
  File "bin/train.py", line 10, in <module>
    from lib.nn_model.model import get_nn_model
  File "/home/gmo/debug_seq2seq/lib/nn_model/model.py", line 4, in <module>
    from seq2seq.models import SimpleSeq2seq
  File "build/bdist.linux-x86_64/egg/seq2seq/__init__.py", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/seq2seq/cells.py", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/recurrentshop/__init__.py", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/recurrentshop/engine.py", line 3, in <module>
ImportError: cannot import name initializers"

Can anyone tell me how to fix this? Thanks

**Comment by TWJxi** [comment]
Have you succeeded？
